title: Kundalini Coding, practicing balanced coding.
description: Kundalini Coding is a blog I started to share my environmental coding practices. I strive to maintain a healthy lifestyle in terms of Mind, Body, and Spirit; and here is where I attempt to apply those to coding.
permalink: :title/
baseurl: # the subpath of your site, e.g. /blog
url: "http://www.kundalinicoding.com" # the base hostname & protocol for your site, e.g. http://example.com:

# Author Settings
author: David Trentham # add your name
author-img:  # add your photo
about-author: Computer Science Major, former United States Marine, and travel enthusiast. # add description
twitter: DavidTrentham85 
github: DavidTrentham # add your Github handle
linkedin: David-Trentham # add your Linkedin handle
email: David.Trentham@protonmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: /page/:num

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
